siteadmin_homepage:
    pattern:  /
    defaults: { _controller: siteadminBundle:Default:index }
siteadmin_avion_lister:
    pattern: /avion/
    defaults: { _controller: siteadminBundle:Avion:lister }
siteadmin_avion_ajouter:
    pattern: /avion/ajouter
    defaults: { _controller: siteadminBundle:Avion:ajouter }
siteadmin_avion_modifier:
    pattern: /avion/modifer/{id}
    defaults: { _controller: siteadminBundle:Avion:modifier }
siteadmin_avion_supprimer:
    pattern: /avion/supprimer/{id}
    defaults: { _controller: siteadminBundle:Avion:supprimer }
siteadmin_vol_lister:
    pattern: /vol/
    defaults: { _controller: siteadminBundle:Vol:lister }
siteadmin_vol_ajouter:
    pattern: /vol/ajouter
    defaults: { _controller: siteadminBundle:Vol:ajouter }
siteadmin_vol_modifier:
    pattern: /vol/modifier/{id}
    defaults: { _controller: siteadminBundle:Vol:modifier }
siteadmin_vol_supprimer:
    pattern: /vol/supprimer/{id}
    defaults: { _controller: siteadminBundle:Vol:supprimer }
siteadmin_vol_pdf:
    pattern: /vol/pdf/{id}
    defaults: { _controller: siteadminBundle:Vol:generatePdf }


siteadmin_personnel_lister:
    pattern: /personnel/
    defaults: { _controller: siteadminBundle:personnel:lister }
siteadmin_personnel_ajouter:
    pattern: /personnel/ajouter
    defaults: { _controller: siteadminBundle:personnel:ajouter }
siteadmin_personnel_modifier:
    pattern: /personnel/modifier/{id}
    defaults: { _controller: siteadminBundle:personnel:modifier }
siteadmin_personnel_supprimer:
    pattern: /personnel/supprimer/{id}
    defaults: { _controller: siteadminBundle:personnel:supprimer }
siteadmin_reservation_lister:
    pattern: /reservation/
    defaults: { _controller: siteadminBundle:reservation:lister }
siteadmin_reservation_accepter:
    pattern: /reservation/accepter/{id}
    defaults: { _controller: siteadminBundle:reservation:accepter}
siteadmin_reservation_refuser:
    pattern: /reservation/refuser/{id}
    defaults: { _controller: siteadminBundle:reservation:refuser}
siteadmin_reservation_supprimer:
    pattern: /reservation/supprimer/{id}
    defaults: { _controller: siteadminBundle:reservation:supprimer}


#FOS
fos_user_security:
    resource: "routing/security.xml"

fos_user_profile:
    resource: "routing/profile.xml"
    prefix: /profile

fos_user_register:
    resource: "routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "routing/change_password.xml"
    prefix: /profile