security:
    providers:
        fos_userbundle:
            id: fos_user.user_provider.username
    firewalls:
        main:
            pattern: .*
            form_login:
                provider: fos_userbundle
                csrf_provider: form.csrf_provider
                always_use_default_target_path: true
                #default_target_path: /admin/
                default_target_path: /login-check
                check_path: fos_user_security_check
                #login-path: fos_user_security_login
                login-path: loginredirect
            logout:
                path: fos_user_security_logout
            anonymous:    true
    access_control:
        - { path: /admin/login, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: /admin/login_check, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: /admin/*, role: ROLE_ADMIN }
        - { path: /reserver/*, role: ROLE_PASSAGER }
#        - { path: admin/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
#        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
